DROP TABLE manager_ai_settings
DROP TABLE assessment_project_access;
DROP TABLE assessment_project_question;
DROP TABLE assessment_project;
DROP TABLE staff_evaluation_question;
DROP TABLE staff_evaluation_answer;
DROP TABLE staff_evaluation_user;
DROP TABLE staff_evaluation;
DROP TABLE question;
DROP TABLE user_responsible;
DROP TABLE user_project_role;
DROP TABLE user_role;
DROP TABLE user_technology;
DROP TABLE users;
DROP TABLE technology;
DROP TABLE project_role;
DROP TABLE career_level;
DROP TABLE skill;
delete from flyway_schema_history where version in ('1.0.0.0');
