CREATE TABLE IF NOT EXISTS skill
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled  BOOLEAN DEFAULT TRUE NOT NULL,
    code     VARCHAR(40)          NOT NULL,
    name     VARCHAR(100)         NOT NULL,
    position integer              NOT NULL,
    CONSTRAINT unq_skill_code UNIQUE (code),
    CONSTRAINT unq_skill_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS career_level
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled  BOOLEAN DEFAULT TRUE NOT NULL,
    code     VARCHAR(40)          NOT NULL,
    name     VARCHAR(100)         NOT NULL,
    position integer              NOT NULL,
    CONSTRAINT unq_career_level_code UNIQUE (code),
    CONSTRAINT unq_career_level_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS project_role
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled  BOOLEAN DEFAULT TRUE NOT NULL,
    code     VARCHAR(40)          NOT NULL,
    name     VARCHAR(100)         NOT NULL,
    position INTEGER              NOT NULL,
    CONSTRAINT unq_project_role_code UNIQUE (code),
    CONSTRAINT unq_project_role_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    middle_name         VARCHAR(255),
    password            VARCHAR(255),
    username            VARCHAR(255),
    email               VARCHAR(255),
    labor_code_position VARCHAR(255),
    responsible_id      BIGINT,
    current_level_id    BIGINT,
    project_role_id     BIGINT,
    CONSTRAINT fk_users_project_role_id FOREIGN KEY (project_role_id) REFERENCES project_role (id),
    CONSTRAINT fk_users_current_level_id FOREIGN KEY (current_level_id) REFERENCES career_level (id),
    CONSTRAINT fk_users_responsible_id FOREIGN KEY (responsible_id) REFERENCES users (id),
    CONSTRAINT unq_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS user_role
(
    user_id BIGINT,
    role    VARCHAR(255),
    CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT unq_user_role UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS staff_evaluation
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status    VARCHAR(40) DEFAULT 'DRAFT' NOT NULL,
    date_from DATE                        NOT NULL,
    date_to   DATE                        NOT NULL,
    name      VARCHAR(255)                NOT NULL,
    CONSTRAINT chk_staff_evaluation_status CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED'))
);

CREATE TABLE IF NOT EXISTS question
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled         BOOLEAN DEFAULT TRUE NOT NULL,
    area_knowledge  VARCHAR(500)         NOT NULL,
    project_role_id BIGINT               NOT NULL,
    section         VARCHAR(500)         NOT NULL,
    skill_id        BIGINT               NOT NULL,
    text            VARCHAR(500)         NOT NULL,
    uuid            VARCHAR(255)         NOT NULL,
    CONSTRAINT fk_question_project_role_id FOREIGN KEY (project_role_id) REFERENCES project_role (id),
    CONSTRAINT fk_skill_skill_id FOREIGN KEY (skill_id) REFERENCES skill (id),
    CONSTRAINT unq_question_uuid UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS staff_evaluation_user
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_message     VARCHAR(4000),
    staff_evaluation_id  BIGINT,
    user_id              BIGINT,
    status               VARCHAR(40) DEFAULT 'NEW' NOT NULL,
    verified_by          BIGINT,
    CONSTRAINT fk_staff_evaluation_user_staff_evaluation_id FOREIGN KEY (staff_evaluation_id) REFERENCES staff_evaluation (id),
    CONSTRAINT fk_staff_evaluation_user_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_staff_evaluation_user_verified_by FOREIGN KEY (verified_by) REFERENCES users (id),
    CONSTRAINT chk_staff_evaluation_user_status CHECK (status IN ('NEW', 'IN_PROGRESS', 'FEEDBACK', 'VERIFICATION', 'COMPLETED'))
);

CREATE TABLE IF NOT EXISTS staff_evaluation_answer
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response                 VARCHAR(40),
    question_id              BIGINT,
    staff_evaluation_user_id BIGINT,
    verified_response        VARCHAR(40),
    verification_comment     VARCHAR(4000),
    CONSTRAINT fk_staff_evaluation_answer_question_id FOREIGN KEY (question_id) REFERENCES question (id),
    CONSTRAINT fk_staff_evaluation_answer_user_id FOREIGN KEY (staff_evaluation_user_id) REFERENCES staff_evaluation_user (id)
);

CREATE TABLE IF NOT EXISTS staff_evaluation_question
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_evaluation_id BIGINT,
    question_id         BIGINT,
    position            INTEGER NOT NULL,
    CONSTRAINT fk_staff_evaluation_question_staff_evaluation_id FOREIGN KEY (staff_evaluation_id) REFERENCES staff_evaluation (id),
    CONSTRAINT fk_staff_evaluation_question_question_id FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE TABLE IF NOT EXISTS assessment_project
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active      BOOLEAN DEFAULT TRUE NOT NULL,
    description VARCHAR(1000),
    name        VARCHAR(255) NOT NULL,
    owner_id    BIGINT NOT NULL,
    CONSTRAINT fk_assessment_project_owner_id FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT unq_assessment_project_owner_id_name UNIQUE (owner_id, name)
);

CREATE TABLE IF NOT EXISTS assessment_project_question
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT NOT NULL,
    question_id     BIGINT NOT NULL,
    career_level_id BIGINT NOT NULL,
    CONSTRAINT fk_assessment_project_question_project_id FOREIGN KEY (project_id) REFERENCES assessment_project (id),
    CONSTRAINT fk_assessment_project_question_question_id FOREIGN KEY (question_id) REFERENCES question (id),
    CONSTRAINT fk_assessment_project_question_career_level_id FOREIGN KEY (career_level_id) REFERENCES career_level (id),
    CONSTRAINT unq_assessment_project_question UNIQUE (project_id, question_id)
);

CREATE TABLE IF NOT EXISTS assessment_project_access
(
    project_id BIGINT NOT NULL,
    manager_id BIGINT NOT NULL,
    CONSTRAINT fk_assessment_project_access_project_id FOREIGN KEY (project_id) REFERENCES assessment_project (id) ON DELETE CASCADE,
    CONSTRAINT fk_assessment_project_access_manager_id FOREIGN KEY (manager_id) REFERENCES users (id),
    CONSTRAINT unq_assessment_project_access UNIQUE (project_id, manager_id)
);
